sudo: required

language: python

services:
- docker

python:
- 3.4
- 3.5

install:
- pip install tox-travis

script:
- tox
- docker pull schana/python3-debuild
- docker run -v $TRAVIS_BUILD_DIR:/mnt/build schana/python3-debuild
